# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_coloniasFin.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(992, 687)
        Dialog.setStyleSheet("background-color: rgb(255, 255, 255);")
        Dialog.setSizeGripEnabled(False)
        self.lblLogo1 = QtWidgets.QLabel(Dialog)
        self.lblLogo1.setGeometry(QtCore.QRect(20, 20, 201, 51))
        self.lblLogo1.setText("")
        self.lblLogo1.setObjectName("lblLogo1")
        self.lblLogo2 = QtWidgets.QLabel(Dialog)
        self.lblLogo2.setGeometry(QtCore.QRect(880, 20, 81, 61))
        self.lblLogo2.setText("")
        self.lblLogo2.setObjectName("lblLogo2")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(20, 90, 661, 411))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.lblImage = QtWidgets.QLabel(self.groupBox)
        self.lblImage.setGeometry(QtCore.QRect(18, 30, 621, 351))
        self.lblImage.setMouseTracking(True)
        self.lblImage.setText("")
        self.lblImage.setObjectName("lblImage")
        self.progressBar = QtWidgets.QProgressBar(self.groupBox)
        self.progressBar.setGeometry(QtCore.QRect(280, 200, 118, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.lblProcess = QtWidgets.QLabel(self.groupBox)
        self.lblProcess.setGeometry(QtCore.QRect(280, 180, 81, 16))
        self.lblProcess.setObjectName("lblProcess")
        self.btnViewRes = QtWidgets.QPushButton(self.groupBox)
        self.btnViewRes.setGeometry(QtCore.QRect(280, 230, 91, 23))
        self.btnViewRes.setObjectName("btnViewRes")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 390, 251, 16))
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(560, 10, 91, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(20, 10, 391, 20))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(690, 510, 271, 151))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 251, 101))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.btnRoot = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnRoot.setObjectName("btnRoot")
        self.gridLayout.addWidget(self.btnRoot, 0, 0, 1, 1)
        self.btnLoad = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnLoad.setObjectName("btnLoad")
        self.gridLayout.addWidget(self.btnLoad, 0, 1, 1, 1)
        self.btnProcess = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnProcess.setObjectName("btnProcess")
        self.gridLayout.addWidget(self.btnProcess, 1, 0, 1, 1)
        self.btnLimpiar = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnLimpiar.setObjectName("btnLimpiar")
        self.gridLayout.addWidget(self.btnLimpiar, 1, 1, 1, 1)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 110, 251, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnRemove = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.btnRemove.setObjectName("btnRemove")
        self.horizontalLayout_2.addWidget(self.btnRemove)
        self.btnAdd = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.btnAdd.setObjectName("btnAdd")
        self.horizontalLayout_2.addWidget(self.btnAdd)
        self.groupBox_4 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 510, 661, 151))
        self.groupBox_4.setStyleSheet("border-color: rgb(207, 207, 207);\n"
"")
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.lblFolder_2 = QtWidgets.QLabel(self.groupBox_4)
        self.lblFolder_2.setGeometry(QtCore.QRect(10, 1, 141, 20))
        self.lblFolder_2.setObjectName("lblFolder_2")
        self.scrollArea = QtWidgets.QScrollArea(self.groupBox_4)
        self.scrollArea.setGeometry(QtCore.QRect(10, 20, 641, 121))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 639, 119))
        self.scrollAreaWidgetContents.setAutoFillBackground(False)
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.listImags = QtWidgets.QListWidget(self.scrollAreaWidgetContents)
        self.listImags.setGeometry(QtCore.QRect(10, 10, 621, 101))
        self.listImags.setDragEnabled(False)
        self.listImags.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.listImags.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.listImags.setObjectName("listImags")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.groupBoxRes = QtWidgets.QGroupBox(Dialog)
        self.groupBoxRes.setGeometry(QtCore.QRect(700, 90, 271, 291))
        self.groupBoxRes.setTitle("")
        self.groupBoxRes.setObjectName("groupBoxRes")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.groupBoxRes)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 40, 251, 231))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lblWell2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.lblWell2.setText("")
        self.lblWell2.setAlignment(QtCore.Qt.AlignCenter)
        self.lblWell2.setObjectName("lblWell2")
        self.gridLayout_2.addWidget(self.lblWell2, 1, 1, 1, 1)
        self.lblWell6 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.lblWell6.setText("")
        self.lblWell6.setAlignment(QtCore.Qt.AlignCenter)
        self.lblWell6.setObjectName("lblWell6")
        self.gridLayout_2.addWidget(self.lblWell6, 2, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 1, 0, 1, 1)
        self.lblWell3 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.lblWell3.setText("")
        self.lblWell3.setAlignment(QtCore.Qt.AlignCenter)
        self.lblWell3.setObjectName("lblWell3")
        self.gridLayout_2.addWidget(self.lblWell3, 2, 1, 1, 1)
        self.lblWell5 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.lblWell5.setText("")
        self.lblWell5.setAlignment(QtCore.Qt.AlignCenter)
        self.lblWell5.setObjectName("lblWell5")
        self.gridLayout_2.addWidget(self.lblWell5, 1, 3, 1, 1)
        self.lblWell1 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.lblWell1.setText("")
        self.lblWell1.setAlignment(QtCore.Qt.AlignCenter)
        self.lblWell1.setObjectName("lblWell1")
        self.gridLayout_2.addWidget(self.lblWell1, 0, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 2, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 2, 0, 1, 1)
        self.lblWell4 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.lblWell4.setText("")
        self.lblWell4.setAlignment(QtCore.Qt.AlignCenter)
        self.lblWell4.setObjectName("lblWell4")
        self.gridLayout_2.addWidget(self.lblWell4, 0, 3, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 1, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 2, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.groupBoxRes)
        self.label_16.setGeometry(QtCore.QRect(70, 10, 121, 20))
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.btnSwitch = QtWidgets.QPushButton(Dialog)
        self.btnSwitch.setGeometry(QtCore.QRect(770, 400, 122, 23))
        self.btnSwitch.setText("")
        self.btnSwitch.setObjectName("btnSwitch")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "ColonyCounter2001XD"))
        self.lblProcess.setText(_translate("Dialog", "Procesando..."))
        self.btnViewRes.setText(_translate("Dialog", "Ver Resultados"))
        self.label_2.setText(_translate("Dialog", "Imagen"))
        self.btnRoot.setText(_translate("Dialog", "Seleccionar imágenes"))
        self.btnLoad.setText(_translate("Dialog", "Cargar imágenes"))
        self.btnProcess.setText(_translate("Dialog", "Procesar imágenes"))
        self.btnLimpiar.setText(_translate("Dialog", "Limpiar"))
        self.btnRemove.setText(_translate("Dialog", "<<"))
        self.btnAdd.setText(_translate("Dialog", ">>"))
        self.lblFolder_2.setText(_translate("Dialog", "Imágenes disponibles"))
        self.label_6.setText(_translate("Dialog", "Pozo 2"))
        self.label_9.setText(_translate("Dialog", "Pozo 6"))
        self.label_8.setText(_translate("Dialog", "Pozo 3"))
        self.label_7.setText(_translate("Dialog", "Pozo 5"))
        self.label_4.setText(_translate("Dialog", "Pozo 1"))
        self.label_5.setText(_translate("Dialog", "Pozo 4"))
        self.label_16.setText(_translate("Dialog", "Resultados del Conteo"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

